include = ["pyproject.toml", "src/**/*.py", "notebooks/**/*.ipynb"]
extend-include = ["*.ipynb"]

# exclude = ["**/tests/**", "**/test_*.py", "**/tests.py"]

# Same as Black.
line-length = 80
indent-width = 4

# Assume Python 3.9
target-version = "py312"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
# select = ["ALL"]
select = [
    "D",   # pydocstyle (Docstrings)
    "ANN", # flake8-annotations (Anotações de tipo)
    "E",   # pycodestyle (Erros)
    "W",   # pycodestyle (Avisos)
    "F",   # Pyflakes (Verificações de erros lógicos)
    "I",   # isort (Ordenação de imports)
    "C4",  # flake8-comprehensions (Compreensões mais idiomáticas)
    "B",   # flake8-bugbear (Bugs e más práticas de design)
    "A",   # flake8-builtins (Shadowing de built-ins)
    "SIM", # flake8-simplify (Simplificação de código)
    "PTH", # flake8-use-pathlib (Uso de pathlib em vez de os.path)
    "RUF", # Regras específicas do Ruff
    "Q",   # flake8-quotes (Consistência de aspas)
]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
